---

language: go

dist: focal

services:
  - docker

go:
  - '1.15'

deploy:
  - provider: releases
    api_key:
      secure: 'z2vvV01TgvGVvG/zfUpQti6J2NdZMyuRmq2gj/rC2JFfoU9PdjL716bVngdNQep0zExEXMrxZB638X5Z4KBU5hRxL8lxh1jasAjP0Hvv53UpUpM/r76lt4CIOnccQ1n400Y4KwM0l19cv5891zeGHMbZfi3XmpBFTd7q+fMOPLSn9tPmTcEeVvTuhEx9g/uGA+5DfZdzzzNy+wwJoi6fhkCfe09ScjlArKcNEVykt+nw38Sz8UvHRUdckvhTUsj8c56uoyL6x7JARZYOqzYHOuP7XnGPOvVL/NoqvQWu9tb8DxMMAIbtSqMjnDZGkBJiJFXaLqE3Xxv3ewEj/nWkwxNxwtXKV5PiD0d3M4xmI48P5EQ4WQldT5ta2XnFJ11JvS/O7nvQos8b+TQkIvoKZxCkhzMCjM347jwMGDytOnnwGhE1F7KTsVLkysQ4+dWmCAqgelSG/U5hAxEDXyySw3qbmf7jLpDR8QMsyGB+eaM0Lod9Eqrets2Qra8MHAonM8TDAMTyeIPshtI3TVIGZdQy2XeqgIezU39ydKpOfu3KfnJ1QNhJWnIBHjGnjz7TYEExSZygnBtGyHCCHrFBjDfYY+MWRzJ0zwxLzhezgVpuLq/ZTnsUR2h7ALXOJWAOBFaD9T7w6xhTx51CheULvQLpAK3FOToBDvdS0RLpsR8='
    file:
      - dist/ghostunnel-${TRAVIS_TAG}-linux-amd64-with-pkcs11
      - dist/ghostunnel-${TRAVIS_TAG}-linux-arm64-with-pkcs11
      - dist/ghostunnel-${TRAVIS_TAG}-darwin-amd64-with-pkcs11
      - dist/ghostunnel-${TRAVIS_TAG}-windows-386-with-pkcs11.exe
      - dist/ghostunnel-${TRAVIS_TAG}-windows-amd64-with-pkcs11.exe
      - dist/sha256sums.txt
      - dist/ghostunnel-${TRAVIS_TAG}.man
    draft: true
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker buildx build --push -t ghostunnel/ghostunnel:${TRAVIS_TAG} --platform linux/amd64,linux/arm64,linux/arm/v7 .
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker buildx build --push -t ghostunnel/ghostunnel:latest --platform linux/amd64,linux/arm64,linux/arm/v7 .
    skip_cleanup: true
    on:
      branch: master

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker.io
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker buildx version
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use
  - go get github.com/mattn/goveralls
  - go get github.com/karalabe/xgo

install:
  # Compile with CGO on/off for testing
  - export GO111MODULE=on
  - CGO_ENABLED=0 go build -o ghostunnel-${TRAVIS_BRANCH}-linux-amd64-without-pkcs11 .
  - CGO_ENABLED=1 go build -tags nopkcs11 -o ghostunnel-${TRAVIS_BRANCH}-linux-amd64-without-pkcs11-but-with-cgo .
  - CGO_ENABLED=1 go build -o ghostunnel-${TRAVIS_BRANCH}-linux-amd64-with-pkcs11 .
  # Build Docker container
  - make docker-build
  # Make sure Docker image runs
  - docker run --rm ghostunnel/ghostunnel --version
  # Cross-compile dist binaries
  - GO_VERSION=${TRAVIS_GO_VERSION} VERSION=${TRAVIS_BRANCH} make -f Makefile.dist dist

script:
  # Run tests inside Docker (guarantees that we have proper PKCS11 test setup)
  - GO_VERSION=${TRAVIS_GO_VERSION} make docker-test

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile coverage-merged.out -service=travis-ci
